services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: ecomarket-db
    environment:
      POSTGRES_DB: ecomarket_db
      POSTGRES_USER: ecomarket_user
      POSTGRES_PASSWORD: ecomarket_pass123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecomarket-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecomarket_user -d ecomarket_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Backend Spring Boot
  backend:
    build:
      context: ./backend-v2
      dockerfile: Dockerfile
    container_name: ecomarket-backend
    environment:
      # Database: PostgreSQL (usando nombre del servicio Docker)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecomarket_db
      SPRING_DATASOURCE_USERNAME: ecomarket_user
      SPRING_DATASOURCE_PASSWORD: ecomarket_pass123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      
      # JWT - Clave de 64+ caracteres para HS512
      JWT_SECRET: ${JWT_SECRET:-09QK6DHuATCn383txu1Z1B6ybjkpuA163FjgWTdu4emOixDQgTqJXS20XoYofFaEyP1Uak3p1BqXzc24kgmQ==}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      
      # File Upload
      FILE_UPLOAD_DIR: /app/uploads
      FILE_MAX_SIZE: 10MB
      
      # CORS
      CORS_ALLOWED_ORIGINS: http://localhost,http://localhost:80,http://frontend
      
      # Server
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev
      
      # AWS S3
      AWS_S3_ENABLED: "true"
      AWS_S3_BUCKET_NAME: "ecomarket-images-prod"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "us-east-1"
    ports:
      - "8080:8080"
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - ecomarket-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ecomarket/api/health"]
      interval: 30s
      timeout: 10s
    #   retries: 5
    #   start_period: 60s
    restart: unless-stopped

  # Frontend Angular con Nginx
  frontend:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    container_name: ecomarket-frontend
    ports:
      - "3000:80"
    networks:
      - ecomarket-network
    depends_on:
      - backend
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    restart: unless-stopped

networks:
  ecomarket-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local
